version: "2.1"

services:
  dc-protocol-stage:
    container_name: dc-protocol
    build: .
    restart: on-failure
    environment:
      - hostname=127.0.0.1
      # - blockTime=0
      # - port=8546
      # - defaultBalanceEther=100000
      # - gasPrice=1
      # - gasLimit=7992181
      # - mnemonic='candy, maple cake sugar pudding cream honey rich smooth crumble sweet treat'
    ports:
      - 127.0.0.1:8545:8545